# Generated by Django 4.2.4 on 2023-09-18 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="schedule",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 18, 12, 47, 30, 608180)
            ),
        ),
    ]
