# Generated by Django 4.2.4 on 2023-08-25 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_course_image_alter_course_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="schedule",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 25, 8, 27, 30, 665871)
            ),
        ),
    ]
