# Generated by Django 4.2.4 on 2023-08-27 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_course_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="schedule",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 27, 2, 6, 55, 89920)
            ),
        ),
    ]
